# Generated by Django 4.1.2 on 2022-11-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('part', 'Part-Time'), ('full', 'Full-Time')], max_length=10),
        ),
    ]
