# Generated by Django 4.1.2 on 2022-12-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_experience'),
        ('posts', '0004_alter_post_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interest',
            field=models.ManyToManyField(to='user.user'),
        ),
    ]
