# Generated by Django 4.1.2 on 2022-12-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recruiter_id',
            field=models.IntegerField(default=-1),
        ),
    ]
