# Generated by Django 4.1.2 on 2022-12-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offers_post_alter_offers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=9),
        ),
    ]
