# Generated by Django 4.1.2 on 2022-11-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Recruiter', 'recruiter'), ('Candidate', 'candidate')], max_length=9)),
                ('profile_bio', models.TextField(blank=True, max_length=500)),
                ('skills', models.TextField()),
                ('github', models.CharField(blank=True, max_length=50)),
                ('experience', models.IntegerField()),
                ('education', models.TextField(blank=True)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
