# Generated by Django 4.1.2 on 2022-11-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_experience_alter_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
