# Generated by Django 4.1.2 on 2022-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate')], default='Recruiter', max_length=9),
        ),
    ]
