# Generated by Django 4.1.2 on 2022-11-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_bio', models.CharField(max_length=500)),
                ('zipcode', models.IntegerField()),
                ('skills', models.TextField()),
                ('github', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('education', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
